# Generated by Django 5.1.7 on 2025-03-12 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('horario_de_trabajo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('horario_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('E', 'Entregado'), ('N', 'No entregado')], default='N', max_length=1)),
                ('empleado_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.empleado')),
            ],
        ),
    ]
